Jabber:
    JID: bot@domain.com
    Pass: mybotpass
    Server: talk.google.com
    Privl:
        - me@domain.com
Twitter:
    consumer_key: <consumer_key>
    consumer_secret: <consumer_secret>
    oauth_token: <oauth_token>
    oauth_secret: <oauth_secret>